### ISSUE TITLE
Compile fails due to new tsetse check

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_typescript#146]
/cc @heathkit
updating Angular to rules_typescript at head
```
compiling //packages/core/test/render3:render3_lib
Compilation failed TypeError: tsutils.isThenableType is not a function
    at Object.checkForTruthy [as handlerFunction] (/usr/local/google/home/alexeagle/.cache/bazel/_bazel_alexeagle/5c094f47f582dc47fc598194e749d5c0/execroot/angular/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsetse/rules/ban_expect_truthy_promise_rule.js:70:22)
    at run (/usr/local/google/home/alexeagle/.cache/bazel/_bazel_alexeagle/5c094f47f582dc47fc598194e749d5c0/execroot/angular/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsetse/checker.js:92:37)
```
my guess is that tsc_wrapped is seeing the user's node_modules directory instead of its own packaged deps in @build_bazel_rules_typescript_tsc_wrapped_deps

**Comment by alexeagle** [comment]
It's another case of #88

**Comment by kara** [comment]
For anyone who might run into this, the following worked for me

```bash
bazel clean --expunge
```
