### ISSUE TITLE
Flaky execution of workers

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_typescript#166]
@hansl observed some failures on circleci that were fixed by re-running:

https://circleci.com/gh/angular/devkit/8171#build-timing 
https://circleci.com/gh/angular/devkit/8234
```
[40 / 47] Compiling TypeScript (devmode) //packages/angular_devkit/core:spec; 23s worker ... (3 actions running)

ERROR: /home/circleci/ng/packages/angular_devkit/schematics/BUILD:86:1: Compiling TypeScript (devmode) //packages/angular_devkit/schematics:spec failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/bazel-workers/worker-1-TypeScriptCompile.log ---8<---8<---
Starting TypeScript compiler persistent worker...
---8<---8<--- End of log ---8<---8<---

INFO: Elapsed time: 107.947s, Critical Path: 61.69s

FAILED: Build did NOT complete successfully
```

https://circleci.com/gh/angular/devkit/8274
```
[40 / 47] Compiling TypeScript (devmode) //packages/angular_devkit/core:spec; 2s worker ... (2 actions, 1 running)

ERROR: /home/circleci/ng/packages/angular_devkit/schematics_cli/BUILD:11:1: Compiling TypeScript (devmode) //packages/angular_devkit/schematics_cli:schematics-cli failed: Worker process quit or closed its stdin stream when we tried to send a WorkRequest:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.doFlush(CodedOutputStream.java:2985)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.write(CodedOutputStream.java:2917)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeLazy(CodedOutputStream.java:2936)
	at com.google.protobuf.ByteString$LiteralByteString.writeTo(ByteString.java:1337)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytesNoTag(CodedOutputStream.java:2735)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytes(CodedOutputStream.java:2708)
	at com.google.protobuf.GeneratedMessageV3.writeString(GeneratedMessageV3.java:2716)
	at com.google.devtools.build.lib.worker.WorkerProtocol$Input.writeTo(WorkerProtocol.java:214)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2783)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2759)
	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkRequest.writeTo(WorkerProtocol.java:975)
	at com.google.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:98)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:284)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.actuallyExec(WorkerSpawnRunner.java:156)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:111)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:97)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:65)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:266)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:273)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:860)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:803)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:110)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:671)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:628)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:412)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:444)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:201)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log, file at /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/bazel-workers/worker-0-TypeScriptCompile.log ---8<---8<---
Starting TypeScript compiler persistent worker...
---8<---8<--- End of log ---8<---8<---

INFO: Elapsed time: 80.366s, Critical Path: 29.23s

FAILED: Build did NOT complete successfully
```

**Comment by Toxicable** [comment]
Also getting this one 
https://github.com/angular/universal/pull/922
https://circleci.com/gh/angular/universal/56?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by alexeagle** [comment]
https://github.com/angular/devkit/commit/fab734b1e910bfeeb9faad0d054031aaaebcffee was intended to fix this (prevent OOM by limiting Bazel's memory, basically presuming that this bug is a dupe of https://github.com/bazelbuild/bazel/issues/3645 )

https://circleci.com/gh/angular/devkit/8599#build-timing (current master HEAD at time of writing) shows this error:
```
INFO: Found 11 targets...

ERROR: /home/circleci/ng/packages/angular_devkit/core/BUILD:11:1: Compiling TypeScript (devmode) //packages/angular_devkit/core:core failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/bazel-workers/worker-1-TypeScriptCompile.log ---8<---8<---
Starting TypeScript compiler persistent worker...
---8<---8<--- End of log ---8<---8<---

INFO: Elapsed time: 68.143s, Critical Path: 23.79s

Exited with code 1
```
and that is after my commit, so it seems this is *not* fixed.

**Comment by qzmfranklin** [comment]
I ran into a similar issue when compiling [`angular-bazel-example`](https://github.com/alexeagle/angular-bazel-example) (the source code has been integrated into my own Bazel project, so the path looks slightly different):

```
20:13 $ bazel build examples/ts/protocol_buffers:devserver 
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //examples/ts/protocol_buffers:devserver (35 packages loaded).
INFO: Found 1 target...
INFO: Writing explanation of rebuilds to 'buildlogs'
INFO: From SkylarkAction examples/ts/protocol_buffers/car.closure.js.tmpl:
WARNING: source-map-support module not installed.
    Stack traces from languages like TypeScript will point to generated .js files.
    Set install_source_map_support = False in @build_bazel_rules_typescript//internal/protobufjs:pbjs_bin to turn off this warning.
    
INFO: From SkylarkAction examples/ts/protocol_buffers/car.js.tmpl:
WARNING: source-map-support module not installed.
    Stack traces from languages like TypeScript will point to generated .js files.
    Set install_source_map_support = False in @build_bazel_rules_typescript//internal/protobufjs:pbjs_bin to turn off this warning.
    
INFO: From Generating typings from examples/ts/protocol_buffers/car.closure.js:
WARNING: source-map-support module not installed.
    Stack traces from languages like TypeScript will point to generated .js files.
    Set install_source_map_support = False in @build_bazel_rules_typescript//internal/protobufjs:pbts_bin to turn off this warning.
    
ERROR: /home/zhongming/git/logi/examples/ts/protocol_buffers/BUILD:37:1: Compiling TypeScript (devmode) //examples/ts/protocol_buffers:app failed: Worker process quit or closed its stdin stream when we tried to send a WorkRequest:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException: Broken pipe
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(Unknown Source)
	at java.base/java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.base/java.io.BufferedOutputStream.write(Unknown Source)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.doFlush(CodedOutputStream.java:2985)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.write(CodedOutputStream.java:2917)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeLazy(CodedOutputStream.java:2936)
	at com.google.protobuf.ByteString$LiteralByteString.writeTo(ByteString.java:1337)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytesNoTag(CodedOutputStream.java:2735)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytes(CodedOutputStream.java:2708)
	at com.google.protobuf.GeneratedMessageV3.writeString(GeneratedMessageV3.java:2716)
	at com.google.devtools.build.lib.worker.WorkerProtocol$Input.writeTo(WorkerProtocol.java:214)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2783)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2759)
	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkRequest.writeTo(WorkerProtocol.java:975)
	at com.google.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:98)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:305)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.actuallyExec(WorkerSpawnRunner.java:154)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:112)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:95)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:63)
	at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:362)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:287)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:294)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:978)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:910)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:120)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:763)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:718)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:457)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:513)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:227)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:400)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log, file at /home/zhongming/.cache/bazel/_bazel_zhongming/e99eb4b42291f3e78ff260c740d00d52/bazel-workers/worker-4-TypeScriptCompile.log ---8<---8<---
Starting TypeScript compiler persistent worker...
---8<---8<--- End of log ---8<---8<---
Target //examples/ts/protocol_buffers:devserver failed to build
INFO: Elapsed time: 3.871s, Critical Path: 2.77s
INFO: 12 processes: 12 linux-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by alexeagle** [comment]
Without a way to reproduce this issue it's going to be hard to isolate and fix. Maybe we need more logging information when it happens, like a dump of the stderr from the node process at the other end of the pipe.
