### ISSUE TITLE
build failures on Buildkite

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/rules_typescript#206]
Hi,

I have noticed that `rules_typescript` no longer builds on Bazel's CI system. Here is a link to a recent build (login required): https://buildkite.com/bazel/rules-typescript-typescript/builds/221#b5be24ee-439c-4e4d-b5e0-638182e7592f

The errors look as follows:

```

ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-5nng-1/bazel/rules-typescript-typescript/internal/BUILD.bazel:37:1: Couldn't build file internal/tsc_wrapped/compiler_host.js: Compiling TypeScript (devmode) //internal:tsc_wrapped failed (Exit 1)
--
  | WARNING: source-map-support module not installed.
  | Stack traces from languages like TypeScript will point to generated .js files.
  |  
  | failed to load main  Error: Cannot find module 'typescript/lib/tsc.js'
  | looked in:
  | typescript/lib/tsc.js,
  | /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/dfdd1ada97d1562dc805297d9f93d6fe/sandbox/3520676976649963374/execroot/build_bazel_rules_typescript/bazel-out/host/bin/internal/tsc.runfiles/typescript/lib/tsc.js,
  | /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/dfdd1ada97d1562dc805297d9f93d6fe/sandbox/3520676976649963374/execroot/build_bazel_rules_typescript/bazel-out/host/bin/internal/tsc.runfiles/build_bazel_rules_typescript/node_modules/typescript/lib/tsc.js,
  | /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/dfdd1ada97d1562dc805297d9f93d6fe/sandbox/3520676976649963374/execroot/build_bazel_rules_typescript/bazel-out/host/bin/internal/tsc.runfiles/build_bazel_rules_typescript_tsc_wrapped_deps/node_modules/typescript/lib/tsc.js
  | at Function.module.constructor._resolveFilename (/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/dfdd1ada97d1562dc805297d9f93d6fe/execroot/build_bazel_rules_typescript/bazel-out/host/bin/internal/tsc_bin_loader.js:258:15)
  | at Function.Module._load (module.js:466:25)
  | at Object.<anonymous> (/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/dfdd1ada97d1562dc805297d9f93d6fe/execroot/build_bazel_rules_typescript/bazel-out/host/bin/internal/tsc_bin_loader.js:290:24)
  | at Module._compile (module.js:635:30)
  | at Object.Module._extensions..js (module.js:646:10)
  | at Module.load (module.js:554:32)
  | at tryModuleLoad (module.js:497:12)
  | at Function.Module._load (module.js:489:3)
  | at Function.Module.runMain (module.js:676:10)
  | at startup (bootstrap_node.js:187:16)
```

Could you provide guidance on how to resolve this please? @alexeagle 

cc: @dslomov

**Comment by gregmagolan** [comment]
This may be related to a silent intermittent yarn failure. I'm going to investigate it this week.

**Comment by alexeagle** [comment]
While we are at it, I'd like to tear down our CircleCI config and make sure we are running everything on buildkite. Also need to follow up on running buildkite as a google3 presubmit.

**Comment by gregmagolan** [comment]
Tracked down the silent yarn install failure that caused this. https://github.com/bazelbuild/rules_nodejs/pull/225 will resolve it.

**Comment by gregmagolan** [comment]
Resolved with https://github.com/bazelbuild/rules_nodejs/commit/534ffaadd8e1a28f1f930107ef75b7ae0632865f (https://github.com/bazelbuild/rules_nodejs/pull/225) but still need to updated rules_typescript to a new rules_nodejs release in its WORKSPACE

**Comment by gregmagolan** [comment]
Updating to the the latest rules_nodejs release 0.1.0 (which includes https://github.com/bazelbuild/rules_nodejs/pull/225) will prevent this from happening in the future.
