### ISSUE TITLE
node_modules attr on ts_library doesn't work when generated

### ISSUE THREAD

**Issue by nimerritt** [bazelbuild/rules_typescript#248]
To give a bit of context, I am trying to track the external NPM dependencies at a more fined grained level than the current setup allows. To do this, each external NPM dependency is a target with it's own node_modules folder along with all transitive dependencies nested. These are referenced by other rules as normal Bazel dependencies and then I construct the full node_modules folder for each ts_library rule and provide it via the `node_modules` attribute. I have this working for the nodejs_binary at execution time, but I can't seem to get it to work for the ts_library, which also needs the .d.ts files from the node_modules at build-time.

As far as I can tell, the existing ts_library rule only works if node_modules is in the actual source-tree and not in the `bazel-bin` or `bazel-genfiles` folder. See https://github.com/bazelbuild/rules_typescript/blob/0b98b47a749f2c6f7803edcbb9916d6722fc34e4/internal/common/tsconfig.bzl#L85-L106

I've produced a minimal example of the bug: https://github.com/Springworks/bazel-generated-node-modules-issue. I may be making a mistake in the rule itself, but it as far as I can tell, this actually isn't supported correctly. I'll try to make a PR to fix this, but I might need some help getting the path joining logic correct.  @alexeagle I'll probably need your help :)
 
```nick@Nicks-MacBook-Pro:bazel-generated-node-modules-issue (master=)$ bazel build //foo
INFO: Analysed target //foo:foo (0 packages loaded).
INFO: Found 1 target...
ERROR: /Users/nick/springworks/bazel-generated-node-modules-issue/foo/BUILD.bazel:4:1: Compiling TypeScript (devmode) //foo:foo failed (Exit 1)
failed to load main  Error: ENOENT: no such file or directory, open '/private/var/tmp/_bazel_nick/b6cc37f53b873222d3145e66f98e0e06/sandbox/darwin-sandbox/1/execroot/bazel_generated_node_modules_issue/foo_generated_deps/node_modules/typescript/lib/lib.es2017.d.ts'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at UncachedFileLoader.loadFile (/private/var/tmp/_bazel_nick/b6cc37f53b873222d3145e66f98e0e06/execroot/bazel_generated_node_modules_issue/external/build_bazel_rules_typescript/internal/tsc_wrapped/file_cache.ts:309:27)
    at /private/var/tmp/_bazel_nick/b6cc37f53b873222d3145e66f98e0e06/execroot/bazel_generated_node_modules_issue/external/build_bazel_rules_typescript/internal/tsc_wrapped/compiler_host.ts:348:34
    at Object.wrap (/private/var/tmp/_bazel_nick/b6cc37f53b873222d3145e66f98e0e06/execroot/bazel_generated_node_modules_issue/external/build_bazel_rules_typescript/internal/tsc_wrapped/perf_trace.ts:54:12)
    at CompilerHost.getSourceFile (/private/var/tmp/_bazel_nick/b6cc37f53b873222d3145e66f98e0e06/execroot/bazel_generated_node_modules_issue/external/build_bazel_rules_typescript/internal/tsc_wrapped/compiler_host.ts:347:22)
    at findSourceFile (/Users/nick/springworks/bazel-generated-node-modules-issue/node_modules/typescript/lib/typescript.js:83827:29)
    at args (/Users/nick/springworks/bazel-generated-node-modules-issue/node_modules/typescript/lib/typescript.js:83739:85)
    at getSourceFileFromReferenceWorker (/Users/nick/springworks/bazel-generated-node-modules-issue/node_modules/typescript/lib/typescript.js:83706:34)
    at processSourceFile (/Users/nick/springworks/bazel-generated-node-modules-issue/node_modules/typescript/lib/typescript.js:83739:13)
Target //foo:foo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.792s, Critical Path: 2.63s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

If I change the `node_modules` reference on `//foo` to point to `node_modules = "@foo_deps//:node_modules"` it works since those are in the source tree of an external workspace.

**Comment by nimerritt** [comment]
So one issue is that https://github.com/Springworks/rules_typescript/blob/0b98b47a749f2c6f7803edcbb9916d6722fc34e4/internal/tsc_wrapped/compiler_host.ts#L463 uses the `nodeModulesPrefix` set https://github.com/bazelbuild/rules_typescript/blob/0b98b47a749f2c6f7803edcbb9916d6722fc34e4/internal/build_defs.bzl#L127 to look up `lib.es2017.d.ts`.

**Comment by alexeagle** [comment]
We have a big refactoring landed in rules_nodejs to do fine-grained deps, and are working on the corresponding change in rules_typescript.
I don't know if it solves your issue but we should wait to investigate more until that's done. See #276

**Comment by nimerritt** [comment]
Yes, those were huge improvements which made much of my work redundant :) Thanks!
