### ISSUE TITLE
Error reporting when missing a node module

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_typescript#25]
Currently with no `node_modules` you get something like

```
/build_bazel_rules_typescript/internal/tsc_wrapped/BUILD.bazel:26:1: Compiling TypeScript (devmode) @build_bazel_rules_typescript//internal/tsc_wrapped:tsc_wrapped failed (Exit 1)
failed to load main  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Module.load (module.js:483:45)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Object.<anonymous> (/home/nathan/.cache/bazel/_bazel_nathan/16731ad4c7c7062932200f437ef52271/execroot/__main__/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped/tsc_loader.js:84:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by alexeagle** [comment]
Fixed in the new nodejs rules
