### ISSUE TITLE
Duplicate identifier errors when importing something from @types

### ISSUE THREAD

**Issue by fortuna** [bazelbuild/rules_typescript#3]
If I import something that I have `@types` for, I get `Duplicate identifier` errors:

For example, this code:
```
import * as electron from 'electron';
export function Hi() {
  console.log('hi');
}
```

Will result in errors like:
```
bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/electron/index.d.ts(15,7): error TS2300: Duplicate identifier 'Point'.
bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/electron/index.d.ts(20,7): error TS2300: Duplicate identifier 'Size'.
bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/electron/index.d.ts(25,7): error TS2300: Duplicate identifier 'Rectangle'.
bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/electron/index.d.ts(45,7): error TS2300: Duplicate identifier 'VibrancyType'.
bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/electron/index.d.ts(456,7): error TS2300: Duplicate identifier 'AppPathName'.
...
```

If I remove the import, compilation finished successfully. This bug pretty much prevents me from using `@types`, and with https://github.com/bazelbuild/rules_typescript/issues/2 we are pretty much prevented from using any type declaration file.

**Comment by alexeagle** [comment]
Hmm, I am using things from `@types` successfully in other repos. Does the rest of the error message give a clue what the second matching declaration was?

**Comment by fortuna** [comment]
Yep, I get the same errors again with ../../.. paths:

```
$ bazel build src/infrastructure
INFO: Found 1 target...
ERROR: /xxx/src/infrastructure/BUILD:4:1: null failed: Process exited with status 2 [sandboxed].
bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge/index.d.ts(8,10): error TS2300: Duplicate identifier 'Byte'.
bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge/index.d.ts(9,10): error TS2300: Duplicate identifier 'Bytes'.
bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge/index.d.ts(10,10): error TS2300: Duplicate identifier 'Hex'.
bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge/index.d.ts(11,10): error TS2300: Duplicate identifier 'Base64'.
bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge/index.d.ts(12,10): error TS2300: Duplicate identifier 'Utf8'.

...(many errors)...

../../../../../../../../firehook/uproxy-cloud-install/node_modules/@types/node-forge/index.d.ts(8,10): error TS2300: Duplicate identifier 'Byte'.
../../../../../../../../firehook/uproxy-cloud-install/node_modules/@types/node-forge/index.d.ts(9,10): error TS2300: Duplicate identifier 'Bytes'.
../../../../../../../../firehook/uproxy-cloud-install/node_modules/@types/node-forge/index.d.ts(10,10): error TS2300: Duplicate identifier 'Hex'.
../../../../../../../../firehook/uproxy-cloud-install/node_modules/@types/node-forge/index.d.ts(11,10): error TS2300: Duplicate identifier 'Base64'.
../../../../../../../../firehook/uproxy-cloud-install/node_modules/@types/node-forge/index.d.ts(12,10): error TS2300: Duplicate identifier 'Utf8'.

...(many errors)...
```

**Comment by fortuna** [comment]
I realized that this is trying to access things from the `node_modules` in the project root (`uproxy-cloud-install`). I'd expect bazel to not look at that.

When I delete the node_modules in my project root, I get a different error:
```
$ rm -rf node_modules/

$ bazel build src/infrastructure
INFO: Found 1 target...
ERROR: /xxx/firehook/uproxy-cloud-install/src/infrastructure/BUILD:4:1: null failed: Process exited with status 1 [sandboxed].
module.js:471
    throw err;
    ^

Error: Cannot find module '/xxx/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/bazel-sandbox/90f73a9a-9086-492e-b086-15fc00875717-0/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/typescript/lib/tsc.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
Use --strategy=Generating=standalone to disable sandboxing for the failing actions.
Target //src/infrastructure:infrastructure failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.229s, Critical Path: 0.56s

```

**Comment by alexeagle** [comment]
Bazel does use the `node_modules` directory in the project, just like other
tools in the JS ecosystem. Note that you didn't have to list your
dependencies again in the `WORKSPACE` file.

**Comment by fortuna** [comment]
FYI, my `WORKSPACE` looks like this:
```python
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "io_bazel_rules_typescript",
    remote = "https://github.com/bazelbuild/rules_typescript.git",
    commit = "4b6b9fde162cd1740d5768c0ba17b242b6098bcb",
)

# Reference: https://github.com/bazelbuild/rules_typescript/blob/master/internal/build_defs.bzl
load("@io_bazel_rules_typescript//:defs.bzl", "node_repositories", "yarn_install")

node_repositories()
yarn_install(package_json = "//:package.json")
```

Should I remove `yarn_install`?

**Comment by fortuna** [comment]
@alexeagle : I think I found what the problem is. tsc is loading the `node-forge` types from two different places:

Module:
```
======== Resolving module 'node-forge' from '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/src/infrastructure/crypto.ts'. ========
Explicitly specified module resolution kind: 'NodeJs'.
'baseUrl' option is set to '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install', using this value to resolve non-relative module name 'node-forge'.
'paths' option is specified, looking for a pattern to match module name 'node-forge'.
Module name 'node-forge', matched pattern '*'.
Trying substitution 'bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/*', candidate module location: 'bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/node-forge'.
Loading module as file / folder, candidate module location '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/node-forge', target file type 'TypeScript'.
File '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/node-forge.ts' does not exist.
File '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/node-forge.tsx' does not exist.
File '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/node-forge.d.ts' does not exist.
Found 'package.json' at '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/node-forge/package.json'.
'package.json' does not have a 'typings' field.
'package.json' does not have a 'types' field.
File '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/node-forge/index.ts' does not exist.
File '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/node-forge/index.tsx' does not exist.
File '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/node-forge/index.d.ts' does not exist.
Trying substitution 'bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/*', candidate module location: 'bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge'.
Loading module as file / folder, candidate module location '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge', target file type 'TypeScript'.
File '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge.ts' does not exist.
File '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge.tsx' does not exist.
File '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge.d.ts' does not exist.
Found 'package.json' at '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge/package.json'.
'package.json' does not have a 'typings' field.
'package.json' does not have a 'types' field.
File '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge/index.ts' does not exist.
File '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge/index.tsx' does not exist.
File '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge/index.d.ts' exist - use it as a name resolution result.
======== Module name 'node-forge' was successfully resolved to '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge/index.d.ts'. ========
```

Type reference:
```
======== Resolving type reference directive 'node-forge', containing file '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/local-fastbuild/bin/src/infrastructure/__inferred type names__.ts', root directory '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types'. ========
Resolving with primary search path '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types'.
Found 'package.json' at '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge/package.json'.
'package.json' does not have a 'typings' field.
'package.json' does not have a 'types' field.
File '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge/index.d.ts' exist - use it as a name resolution result.
Resolving real path for '/usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install/bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/node-forge/index.d.ts', result '/usr/local/google/home/fortuna/firehook/uproxy-cloud-install/node_modules/@types/node-forge/index.d.ts'.
======== Type reference directive 'node-forge' was successfully resolved to '/usr/local/google/home/fortuna/firehook/uproxy-cloud-install/node_modules/@types/node-forge/index.d.ts', primary: true. ========
```

This is part of the generated tsconfig file:
In the generated tsconfig, I have:
```
    "rootDir": "../../../../..",
    "rootDirs": [
      "../../../../..",
      "../../../../../bazel-out/local-fastbuild/genfiles",
      "../../../../../bazel-out/local-fastbuild/bin"
    ],
    "baseUrl": "../../../../..",
    "paths": {
      "*": [
        "bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/*"
        "bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/@types/*"
      ],
      "zone.js": [
        "bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped.runfiles/yarn/installed/node_modules/zone.js/dist/zone.js.d.ts"
      ]
    },
```

When I remove `@types` from the `paths` entry, the problem goes away.
Is that the right fix?

**Comment by alexeagle** [comment]
Thanks for debugging, that does seem like the right fix. The @types entry under paths was needed at some point but probably isn't now.
