### ISSUE TITLE
Initial setup troubles

### ISSUE THREAD

**Issue by evmar** [bazelbuild/rules_typescript#47]
Following the instructions on the front page:

1.  Which version of node rules should I use?  It just says "latest" but doesn't say how to figure out what that should be.

2.  Before you run anything you need a `package.json`, otherwise you get a big error [1].

3.  That's enough to run yarn, but then after you try to use ts_library, you get another big error [2].  Alex says it's because you need a `bazel run @yarn//:yarn -- add -D @bazel/typescript`.

Error [1]:

```
$ bazel run @yarn//:yarn
ERROR: Skipping '@yarn//:yarn': no such package '@yarn//': Traceback (most recent call last):
	File "/usr/local/google/home/evanm/.cache/bazel/_bazel_evanm/f6cc45cea0037091838c829714de86cc/external/build_bazel_rules_nodejs/internal/node_install.bzl", line 100
		ctx.file("yarn.sh", ("#!/bin/bash" + "".joi...])), ...)
	File "/usr/local/google/home/evanm/.cache/bazel/_bazel_evanm/f6cc45cea0037091838c829714de86cc/external/build_bazel_rules_nodejs/internal/node_install.bzl", line 100, in ctx.file
		"".join(["\nROOT=\"$(dirname \"{}\")\"\n...])
	File "/usr/local/google/home/evanm/.cache/bazel/_bazel_evanm/f6cc45cea0037091838c829714de86cc/external/build_bazel_rules_nodejs/internal/node_install.bzl", line 100, in "".join
		"\nROOT=\"$(dirname \"{}\")\"\nNODE=\"{}\"\nSCRIPT=\"{}\"\n(cd \"$ROOT\"; \"$NODE\" \"$SCRIPT\" \"$@\")\n".format(ctx.path(package_json), ctx.path(n...), ..."))
	File "/usr/local/google/home/evanm/.cache/bazel/_bazel_evanm/f6cc45cea0037091838c829714de86cc/external/build_bazel_rules_nodejs/internal/node_install.bzl", line 106, in "\nROOT=\"$
		ctx.path(package_json)
Not a file: /usr/local/google/home/evanm/projects/devserver/package.json
WARNING: Target pattern parsing failed.
ERROR: no such package '@yarn//': Traceback (most recent call last):
	File "/usr/local/google/home/evanm/.cache/bazel/_bazel_evanm/f6cc45cea0037091838c829714de86cc/external/build_bazel_rules_nodejs/internal/node_install.bzl", line 100
		ctx.file("yarn.sh", ("#!/bin/bash" + "".joi...])), ...)
	File "/usr/local/google/home/evanm/.cache/bazel/_bazel_evanm/f6cc45cea0037091838c829714de86cc/external/build_bazel_rules_nodejs/internal/node_install.bzl", line 100, in ctx.file
		"".join(["\nROOT=\"$(dirname \"{}\")\"\n...])
	File "/usr/local/google/home/evanm/.cache/bazel/_bazel_evanm/f6cc45cea0037091838c829714de86cc/external/build_bazel_rules_nodejs/internal/node_install.bzl", line 100, in "".join
		"\nROOT=\"$(dirname \"{}\")\"\nNODE=\"{}\"\nSCRIPT=\"{}\"\n(cd \"$ROOT\"; \"$NODE\" \"$SCRIPT\" \"$@\")\n".format(ctx.path(package_json), ctx.path(n...), ..."))
	File "/usr/local/google/home/evanm/.cache/bazel/_bazel_evanm/f6cc45cea0037091838c829714de86cc/external/build_bazel_rules_nodejs/internal/node_install.bzl", line 106, in "\nROOT=\"$
		ctx.path(package_json)
Not a file: /usr/local/google/home/evanm/projects/devserver/package.json
INFO: Elapsed time: 1.233s
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
```

Error [2]

```
$ bazel build :my_code
ERROR: Skipping ':my_code': error loading package '': Encountered error while reading extension file 'defs.bzl': no such package '@build_bazel_rules_typescript//': /usr/local/google/home/evanm/.cache/bazel/_bazel_evanm/f6cc45cea0037091838c829714de86cc/external/build_bazel_rules_typescript must be an existing directory
WARNING: Target pattern parsing failed.
ERROR: error loading package '': Encountered error while reading extension file 'defs.bzl': no such package '@build_bazel_rules_typescript//': /usr/local/google/home/evanm/.cache/bazel/_bazel_evanm/f6cc45cea0037091838c829714de86cc/external/build_bazel_rules_typescript must be an existing directory
INFO: Elapsed time: 0.081s
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: 
```

**Comment by hectim** [comment]
This is also blocking me. Copied the WORKSPACE and BUILD files with the versions that presumably worked in the past and they fail with an error. 

```
ERROR: error loading package '': Encountered error while reading extension file 'defs.bzl': no such package '@build_bazel_rules_typescript//': .../external/build_bazel_rules_typescript must be an existing directory
ERROR: error loading package '': Encountered error while reading extension file 'defs.bzl': no such package '@build_bazel_rules_typescript//': .../external/build_bazel_rules_typescript must be an existing directory
INFO: Elapsed time: 0.947s
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
```

Updated the versions to the current latest and installed tsickle and rules_typescript as mentioned in  #49. Even tried installing tsutils as mentioned in #88.

```
ERROR: WORKSPACE:18:1: file '@build_bazel_rules_typescript//:defs.bzl' does not contain symbol 'ts_setup_workspace'
ERROR: WORKSPACE:19:1: name 'ts_setup_workspace' is not defined
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.074s
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
```

After spending a fair amount of time, I can't seem to get it to do the most basic of builds. Would be interested in knowing if these rules are still supported or if full attention should be given to bazelbuild/rules_nodejs mentioned #133. Using some custom Parcel rules with that project in the meantime.

**Comment by alexeagle** [comment]
I'm sorry @hectim, you've run into a stale doc. If you install `@bazel/typescript` right now you get a very old version. I had stopped publishing it for a while because all of our repos ask Bazel to fetch it: https://github.com/angular/tsickle/blob/master/WORKSPACE#L31

I'll publish `@bazel/typescript` again right now so no one else falls in this hole. I'm sorry you had such a bad experience!

**Comment by alexeagle** [comment]
I think this has been addressed:
- quickstart is now just `npx @bazel/create` which stamps out these initial files
- we have cleaned up workspace dependencies, there is no longer anything like `ts_setup_dependencies` because we rely only on npm dependencies and packages
- have done a bunch of work over the docs
