### ISSUE TITLE
Can't run mocha on generated .js file

### ISSUE THREAD

**Issue by fortuna** [bazelbuild/rules_typescript#55]
There's something off with the way bazel_typescript generates the modules. When I run mocha on one of the generated .js files, it can't find the `__main__` dependencies:

```
./node_modules/mocha/bin/mocha bazel-out/local-fastbuild/bin/transports/transports_test.js

module.js:471
    throw err;
    ^

Error: Cannot find module '__main__/transports/transports'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /private/var/tmp/_bazel_vini/2d5cfdef207760378b471079ca80358b/execroot/__main__/bazel-out/local-fastbuild/bin/transports/transports_test.js:16:22
    at Object.defineProperty.value (/private/var/tmp/_bazel_vini/2d5cfdef207760378b471079ca80358b/execroot/__main__/bazel-out/local-fastbuild/bin/transports/transports_test.js:5:17)
    at Object.<anonymous> (/private/var/tmp/_bazel_vini/2d5cfdef207760378b471079ca80358b/execroot/__main__/bazel-out/local-fastbuild/bin/transports/transports_test.js:11:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (modul
```

Top of the .js file:
```
$ cat bazel-out/local-fastbuild/bin/transports/transports_test.js
///  <reference types="mocha"/>
///  <reference types="node"/>
(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define("__main__/transports/transports_test", ["require", "exports", "assert", "stream", "__main__/transports/transports"], factory);
    }
})(function (require, exports) {
    "use strict";
```

And my BUILD:
```py
ts_library(
    name = "transports_test",
    srcs = ["transports_test.ts"],
    deps = [
        ":model",
        ":transports",
    ],
    tsconfig = "//:tsconfig.json",
)
```

**Comment by fortuna** [comment]
I guess one of the problems is the lack of runfiles on ts_libraries. I guess I need some sort of `ts_binary`.

**Comment by alexeagle** [comment]
Sorry this one fell through the cracks. As you observe, the development mode JS files have named AMD modules wrapped in UMD. I think this works fine in mocha, but you need `require.js` to be loaded first, then all the sources.

I have a `ts_test` rule in https://github.com/bazelbuild/rules_typescript/pull/72 which uses Karma, maybe this is actually what you want.

**Comment by alexeagle** [comment]
try `ts_web_test`, let me know if you still need something more
