### ISSUE TITLE
bazel build cannot find tsc.js

### ISSUE THREAD

**Issue by codesuki** [bazelbuild/rules_typescript#64]
I am trying to use bazel with my typescript project and after setting up the basics as in the readme I get this error.

```bazel build //...    
..........
INFO: Found 2 targets...
ERROR: /private/var/tmp/_bazel_a13575/0a014a13c52b9c9d10834f80d53a0b06/external/build_bazel_rules_typescript/internal/tsc_wrapped/BUILD.bazel:26:1: Compiling TypeScript (devmode) @build_bazel_rules_typescript//internal/tsc_wrapped:tsc_wrapped failed (Exit 1).
failed to load main  Error: Cannot find module 'typescript/lib/tsc.js'
  looked in:
   typescript/lib/tsc.js,
   /private/var/tmp/_bazel_a13575/0a014a13c52b9c9d10834f80d53a0b06/bazel-sandbox/149211111440408385/execroot/__main__/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped/tsc.runfiles/typescript/lib/tsc.js,
   /private/var/tmp/_bazel_a13575/0a014a13c52b9c9d10834f80d53a0b06/bazel-sandbox/149211111440408385/execroot/__main__/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped/tsc.runfiles/build_bazel_rules_typescript/node_modules/typescript/lib/tsc.js
    at Function.module.constructor._resolveFilename (/private/var/tmp/_bazel_a13575/0a014a13c52b9c9d10834f80d53a0b06/execroot/__main__/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped/tsc_bin_loader.js:137:15)
    at Function.Module._load (module.js:417:25)
    at Object.<anonymous> (/private/var/tmp/_bazel_a13575/0a014a13c52b9c9d10834f80d53a0b06/execroot/__main__/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped/tsc_bin_loader.js:149:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
INFO: Elapsed time: 14.731s, Critical Path: 0.37s
```

WORKSPACE
```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "build_bazel_rules_nodejs",
    remote = "https://github.com/bazelbuild/rules_nodejs.git",
    tag = "0.1.11", # check for the latest tag when you install
)

load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories")

node_repositories(package_json = ["//:package.json"])

local_repository(
    name = "build_bazel_rules_typescript",
    path = "node_modules/@bazel/typescript",
)
```

BUILD.bazel
```
package(default_visibility = ["//visibility:public"])

exports_files(["tsconfig.json"])

# NOTE: this will move to node_modules/BUILD in a later release
filegroup(
     name = "node_modules",
     srcs = glob(["node_modules/**"]),
)
```

package.json
```
...
  "devDependencies": {
    "@bazel/typescript": "0.2.x",
    "tsickle": "^0.25.0",
    "typescript": "2.4.2",
```

The file exists in the `node_modules/typescript/lib` folder.

**Comment by achew22** [comment]
Can you run `bazel run @yarn//:yarn` and try it one more time?

**Comment by codesuki** [comment]
Thanks for the fast reply! I ran it and got the same result afterwards.

**Comment by codesuki** [comment]
I checked out this repo and ran `bazel build //...`. Same error.

**Comment by codesuki** [comment]
After it worked when I checked out this repo and compiled the examples I dug a little deeper and found that the reason it doesn't work is that `rules_typescript` tries to use it's own `node_modules` inside `project/node_modules/@bazel/typescript/node_modules` which is empty. 
I cd'ed into that and did a `yarn install` after which typescript is installed into that sub node_modules directory. It would be preferable if it could use the parents node_modules, which is probably what you supposed to do but is bugging out.
